### ISSUE TITLE
Can we use this?

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#44]
Can we use [this](https://github.com/vsvyatski/ookii.dialogs), as it's under BSD-3 Clause?

**Comment by Smurf-IV** [comment]
- Sort of - yes, but the original code will need the original License.

- The other way is to derive from the original, so that it keeps it's integrity,
Or use Peer programming, where one person looks at the code and describes it, and the the other writes the code to reflect the description (Not a like for like!)

- Another way, is to get the 2 authors to agree to merging the code into the Extended Suite.

**Comment by Wagnerp** [comment]
Could the original licence be stored in the source code itself? Finding the original code is easy. 
[Ookii.Dialogs.zip](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470/files/2846366/Ookii.Dialogs.zip) was downloaded straight from the original authors website.

**Comment by Smurf-IV** [comment]
I think so, Because the 3rd clause states not to endorse derived works with the original name without permission, So if it is not given, the "Code could" still be used due to the 1st 2 clauses.
Remember Krypton is also BSD 3 and permission was given from the author for derived works (Sort of) due to his statement of "releasing it" into github for further development.

Ooki dialogs already overlaps some of the functionality in Krypton Components, so only a subset of the derived work(s) will be used.

**Comment by Wagnerp** [comment]
I have integrated the code. The only thing I changed was the file/folder structure.
